name: Release

on:
  release:
    types: [published]

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # choose the Node.js version suitable for your project

      - name: Install dependencies
        run: npm install

      - name: Run release script
        run: node release-script.js ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
